/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab1p2_hectorflores;

import javax.swing.JOptionPane;

/**
 *
 * @author hecto
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        printPassengers = new javax.swing.JButton();
        sellTicket = new javax.swing.JButton();
        cancelTicket = new javax.swing.JButton();
        dispatch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        printPassengers.setText("Pasajeros a bordo");
        printPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printPassengersActionPerformed(evt);
            }
        });

        sellTicket.setText("Vender boleto");
        sellTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTicketActionPerformed(evt);
            }
        });

        cancelTicket.setText("Cancelar ticket");
        cancelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTicketActionPerformed(evt);
            }
        });

        dispatch.setText("Despachar avión");
        dispatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispatchActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Menu de acciones");

        salir.setText("Salir del menu");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dispatch)
                    .addComponent(cancelTicket)
                    .addComponent(sellTicket)
                    .addComponent(printPassengers)
                    .addComponent(jLabel1)
                    .addComponent(salir))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printPassengers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dispatch)
                .addGap(50, 50, 50)
                .addComponent(salir)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    PalindromaAir metodos = new PalindromaAir();
    Ticket a = new Ticket ("", 800);
    
    public static String capitalizarPrimeraLetra(String input) {
        if (input == null || input.isEmpty()) {
            return input;
        }

        return input.substring(0, 1).toUpperCase() + input.substring(1).toLowerCase();
    }
    
    private void printPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printPassengersActionPerformed
      metodos.printPassengers();
    }//GEN-LAST:event_printPassengersActionPerformed

    private void sellTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTicketActionPerformed
        String name = JOptionPane.showInputDialog("Nombre del pasajero: ");
        name = name.toLowerCase();
        metodos.sellTicket(name);
        name = capitalizarPrimeraLetra(name);
        (metodos.asientos[metodos.firstAvailable() - 1]).setNombre(name);
    }//GEN-LAST:event_sellTicketActionPerformed

    private void cancelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTicketActionPerformed
        String name = JOptionPane.showInputDialog("Nombre del pasajero que desea cancelar su ticket: ");
        if(metodos.cancelTicket(name)){
            JOptionPane.showMessageDialog(null, "Se ha cancelado el ticket de " + name + " exitosamente.");
        } else {
            JOptionPane.showMessageDialog(null, "El pasajero " + name + " no esta registrado en el avion.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cancelTicketActionPerformed

    private void dispatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispatchActionPerformed
        metodos.dispatch();
    }//GEN-LAST:event_dispatchActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelTicket;
    private javax.swing.JButton dispatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton printPassengers;
    private javax.swing.JButton salir;
    private javax.swing.JButton sellTicket;
    // End of variables declaration//GEN-END:variables
}
